#!/usr/bin/env python3
"""Generate the complete project-self-contained Erdős Problem 593 Lean proof.

The output contains the exact transitive closure of the local modules imported
by Erdos593.lean. Local imports are replaced by source text in dependency
order; sorted external Mathlib imports remain at the top of the generated file.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]
ROOT_MODULE = "Erdos593"
ROOT_SOURCE = PROJECT_DIR / "Erdos593.lean"
MODULE_DIR = PROJECT_DIR / "Erdos593"
OUTPUT = PROJECT_DIR / "Erdos593SelfContained.lean"
IMPORT_RE = re.compile(r"^\s*import\s+(.+?)\s*$")


def normalized_text(path: Path) -> str:
    """Read UTF-8 source and normalize line endings for reproducible output."""
    return path.read_text(encoding="utf-8-sig").replace("\r\n", "\n").replace("\r", "\n")


def module_sources() -> dict[str, Path]:
    """Map every available local module name to its source path."""
    sources = {ROOT_MODULE: ROOT_SOURCE}
    for path in sorted(MODULE_DIR.rglob("*.lean")):
        relative = path.relative_to(PROJECT_DIR).with_suffix("")
        sources[".".join(relative.parts)] = path
    return sources


def imports_in(text: str, path: Path) -> list[str]:
    """Extract module names from Lean import commands."""
    imports: list[str] = []
    for line_number, line in enumerate(text.splitlines(), start=1):
        match = IMPORT_RE.match(line)
        if match is None:
            continue
        command = match.group(1).split("--", maxsplit=1)[0].strip()
        names = command.split()
        if not names:
            raise ValueError(f"empty import command at {path}:{line_number}")
        imports.extend(names)
    return imports


def body_without_imports(text: str) -> str:
    """Remove import commands while preserving all declaration source text."""
    lines = [line for line in text.splitlines() if IMPORT_RE.match(line) is None]
    return "\n".join(lines).strip("\n")


def closure_in_dependency_order(
    sources: dict[str, Path],
) -> tuple[list[str], list[str], dict[str, str]]:
    """Return exact reachable local closure, external imports, and source text."""
    texts = {module: normalized_text(path) for module, path in sources.items()}
    dependencies = {
        module: imports_in(text, sources[module]) for module, text in texts.items()
    }
    ordered: list[str] = []
    external: set[str] = set()
    permanent: set[str] = set()
    temporary: list[str] = []

    def visit(module: str) -> None:
        if module in permanent:
            return
        if module in temporary:
            cycle = " -> ".join([*temporary, module])
            raise ValueError(f"cyclic local import graph: {cycle}")
        if module not in sources:
            raise ValueError(f"missing source for local module {module}")

        temporary.append(module)
        for dependency in dependencies[module]:
            if dependency == ROOT_MODULE or dependency.startswith(f"{ROOT_MODULE}."):
                visit(dependency)
            else:
                external.add(dependency)
        temporary.pop()
        permanent.add(module)
        ordered.append(module)

    visit(ROOT_MODULE)
    return ordered, sorted(external), texts


def section_name(module: str) -> str:
    """Create a deterministic, unique Lean section name for a module."""
    safe = re.sub(r"[^A-Za-z0-9_]", "_", module)
    return f"Erdos593SelfContained_Module_{safe}"


def render() -> tuple[str, list[str], list[str]]:
    """Render the generated Lean file and return provenance metrics."""
    sources = module_sources()
    ordered, external, texts = closure_in_dependency_order(sources)

    header = """\
/-!
# Erdős Problem 593: Complete Project-Self-Contained Lean Proof

DO NOT EDIT THIS FILE DIRECTLY.
Regenerate it with scripts/generate_self_contained.py.

## Status

This file is a full, kernel-checkable formal proof of the finite classification
asked for in Erdős Problem 593. It is project-self-contained: it imports no
Erdos593 project module and instead includes the complete local source closure
in dependency order. Its only imports are from the Mathlib version pinned by
this project's lake-manifest.json and lean-toolchain.

For every finite triple system `F`, the final public theorems prove
`F.IsObligatory ↔ F.isolatedReduction.Intrinsic` and, equivalently,
`F.IsObligatory ↔ Constructible F.isolatedReduction`.  Thus this file includes
both directions of the classification: the constructive positive direction
from obligatory complete-bipartite expansion atoms and closure operations, and
the avoidance direction from nonlinearity, failed edge bridges, and odd Berge
cycles via the shift-graph and Erdős--Rado machinery.  Isolated vertices are
handled by the exact isolated-reduction invariance theorem.  The supporting
development includes the bridge-block quotient forest and rooted
running-intersection reconstruction, the finite sequence-lift trace and fibre
analysis, and the required chromatic-cardinal obstruction interfaces.

Generated deterministically from Erdos593.lean and its exact transitive local
import closure. Each source boundary records its relative path and normalized
source SHA-256. Axiom auditing is kept as a separate reproducible check; see
SELF_CONTAINED_BUILD.md.
-/
"""

    # Lean requires imports to precede all ordinary commands, including a
    # module documentation comment.
    chunks = [*(f"import {module}" for module in external), "", header.rstrip(), ""]

    for module in ordered:
        path = sources[module]
        relative = path.relative_to(PROJECT_DIR).as_posix()
        text = texts[module]
        digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
        section = section_name(module)
        body = body_without_imports(text)
        chunks.extend(
            [
                "/- " + "=" * 74,
                f"BEGIN SOURCE MODULE: {module}",
                f"Source: {relative}",
                f"Normalized SHA-256: {digest}",
                "=" * 74 + " -/",
                f"section {section}",
                "",
                body,
                "",
                f"end {section}",
                "/- " + "=" * 74,
                f"END SOURCE MODULE: {module}",
                "=" * 74 + " -/",
                "",
            ]
        )

    rendered = "\n".join(chunks).rstrip() + "\n"
    return rendered, ordered, external


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail unless Erdos593SelfContained.lean is up to date",
    )
    args = parser.parse_args()

    rendered, ordered, external = render()
    digest = hashlib.sha256(rendered.encode("utf-8")).hexdigest()
    line_count = len(rendered.splitlines())

    if args.check:
        if not OUTPUT.exists() or normalized_text(OUTPUT) != rendered:
            print(f"out of date: {OUTPUT}", file=sys.stderr)
            return 1
        action = "checked"
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        with OUTPUT.open("w", encoding="utf-8", newline="\n") as stream:
            stream.write(rendered)
        action = "generated"

    print(
        f"{action} {OUTPUT.name}: "
        f"{len(ordered)} source modules, {len(external)} external imports, "
        f"{line_count} lines, sha256={digest}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
